### ISSUE TITLE
Relative import Path "@graphql-tools/schema" is not prefixed with / or ./ or ../

### ISSUE THREAD

**Issue by ybabts** [vicary/fresh_graphql#1]
When following the setup guide Fresh cannot start due to the file paths not using relative import paths.
```
Watcher File change detected! Restarting!
error: Relative import path "@graphql-tools/schema" not prefixed with / or ./ or ../ and not in import map from "https://deno.land/x/fresh_graphql@v0.3.2/deps.ts"
    at https://deno.land/x/fresh_graphql@v0.3.2/deps.ts:2:38
Watcher Process finished. Restarting on file change...
```
Adding the import paths you have in the module fixes the issue, however that step is not listed in the setup. Whenever you create a module for people to import over the web, it should include relative import paths and full URLS.

**Comment by vicary** [comment]
@ybabts Thanks for reporting, I can reproduce the issue by creating a new project.

I don't think this problem exists before, import maps resolution may have changed in newer Deno versions.

There is an absolute path for `@graphql-tools/schema` from the [`import_map.json`](https://deno.land/x/fresh_graphql@v0.3.2/import_map.json?source#L12), the imports can be picked up by my example.

I think import maps in root project now overrides whatever inside a module, I'll remove my `import_map.json` and use absolute URLs in `deps.ts`.

Please upgrade to v0.3.3 and try again

**Comment by ybabts** [comment]
Using v0.0.3 the issue is still there on a new project
```
error: Relative import path "graphql" not prefixed with / or ./ or ../ and not in import map from "https://esm.sh/v102/@graphql-tools/utils@9.1.0/X-ZS9ncmFwaHFs/deno/utils.js"
    at https://esm.sh/v102/@graphql-tools/utils@9.1.0/X-ZS9ncmFwaHFs/deno/utils.js:34:34850
```
It seems as enough the remote import is the new culprit, they're the ones using an import map. Maybe it's a good idea to make a setup script to make installing this easier. This issue is going to continue until they update `@graphql-tools`.

**Comment by vicary** [comment]
The `graphql` package, alongside `$fresh` itself, is similar to "peerDependencies" in node.js.

I would like the root project to have control over which version we imports, this avoids potential type conflicts when your `@graphql-yoga/common` has an incompatible version of `graphql` than mine. For the sake of perfection I don't even want two versions of `graphql` in the same project even if it's a patch level difference.

The root project has to include `graphql` in its import map to work, I can start working on a setup script if you think this makes sense.

**Comment by vicary** [comment]
I guess the root project has to include `graphql` in its import map, I can start working on a setup script if you think this makes sense.

**Comment by vicary** [comment]
@ybabts I have ported the module into JSR, try install it from there!

https://jsr.io/@vicary/fresh-graphql
